[package]
name = "pi-summary"
description = "Bottom-up summary scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
futures.workspace = true
pi-llm.workspace = true
pi-optimize.workspace = true
pi-pycompat.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
unicode-general-category.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
